CREATE USER PROJECTDB IDENTIFIED BY "oracle123";


GRANT CREATE SESSION TO PROJECTDB;
GRANT CREATE TABLE TO PROJECTDB;
GRANT CREATE SEQUENCE TO PROJECTDB;
GRANT CREATE TRIGGER TO PROJECTDB;
GRANT CREATE PROCEDURE TO PROJECTDB;
GRANT CREATE ROLE TO PROJECTDB;
GRANT UNLIMITED TABLESPACE TO PROJECTDB;


GRANT DBA TO PROJECTDB;

COMMIT;