spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    username: ${ORACLE_USER:projectdb}
    password: ${ORACLE_PASSWORD:oracle123}
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
    database-platform: org.hibernate.dialect.OracleDialect 

encryption:
  key:
    master: ${MASTER_KEY}
    salt: ${KEY_SALT}
    encrypted: ${ENCRYPTED_KEY}