-- ========================================
-- Create Tables Only - PROJECTDB Schema
-- Simple table creation script
-- ========================================

-- Make sure we're in PROJECTDB schema
ALTER SESSION SET CURRENT_SCHEMA = PROJECTDB;

-- Verify current schema
SELECT USER as current_user, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') as current_schema FROM dual;

-- Create sequences first
CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE instructor_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE course_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE enrollment_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;

-- Create tables in correct order (no foreign keys first)

-- 1. Students table
CREATE TABLE students (
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL,
    address VARCHAR2(500) NOT NULL,
    date_of_birth DATE NOT NULL
);

-- 2. Instructors table
CREATE TABLE instructors (
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL,
    department VARCHAR2(100) NOT NULL,
    office_address VARCHAR2(500)
);

-- 3. Users table
CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) NOT NULL,
    department VARCHAR2(100)
);

-- 4. Courses table (references instructors)
CREATE TABLE courses (
    id NUMBER PRIMARY KEY,
    course_code VARCHAR2(20) NOT NULL UNIQUE,
    course_name VARCHAR2(200) NOT NULL,
    credits NUMBER NOT NULL,
    description VARCHAR2(1000),
    instructor_id NUMBER REFERENCES instructors(id)
);

-- 5. Enrollments table (references students and courses)
CREATE TABLE enrollments (
    id NUMBER PRIMARY KEY,
    student_id NUMBER NOT NULL REFERENCES students(id),
    course_id NUMBER NOT NULL REFERENCES courses(id),
    enrollment_number VARCHAR2(100) UNIQUE,
    grade NUMBER,
    status VARCHAR2(50) DEFAULT 'ENROLLED',
    enrollment_date DATE DEFAULT SYSDATE
);

-- 6. Simple audit log table (for triggers)
CREATE TABLE simple_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    action VARCHAR2(10),
    user_name VARCHAR2(100),
    when_done TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    what_changed VARCHAR2(500)
);

COMMIT;

-- Insert some test data
INSERT INTO instructors (id, first_name, last_name, email, phone_number, department, office_address)
VALUES (instructor_seq.NEXTVAL, 'Dr. Alice', 'Johnson', 'alice.johnson@university.edu', '555-123-4567', 'Computer Science', 'Room 201');

INSERT INTO instructors (id, first_name, last_name, email, phone_number, department, office_address)
VALUES (instructor_seq.NEXTVAL, 'Prof. Bob', 'Wilson', 'bob.wilson@university.edu', '555-987-6543', 'Mathematics', 'Room 301');

INSERT INTO students (id, first_name, last_name, email, phone_number, address, date_of_birth)
VALUES (student_seq.NEXTVAL, 'John', 'Doe', 'john.doe@university.edu', '123-456-7890', '123 Main St', DATE '1995-05-15');

INSERT INTO students (id, first_name, last_name, email, phone_number, address, date_of_birth)
VALUES (student_seq.NEXTVAL, 'Jane', 'Smith', 'jane.smith@university.edu', '987-654-3210', '456 Oak Ave', DATE '1996-08-22');

INSERT INTO courses (id, course_code, course_name, credits, description, instructor_id)
VALUES (course_seq.NEXTVAL, 'CS101', 'Programming', 3, 'Basic programming', 1);

INSERT INTO courses (id, course_code, course_name, credits, description, instructor_id)
VALUES (course_seq.NEXTVAL, 'MATH201', 'Calculus', 4, 'Calculus basics', 2);

INSERT INTO enrollments (id, student_id, course_id, enrollment_number, status)
VALUES (enrollment_seq.NEXTVAL, 1, 1, 'ENR-2024-001', 'ENROLLED');

INSERT INTO enrollments (id, student_id, course_id, enrollment_number, status)
VALUES (enrollment_seq.NEXTVAL, 2, 1, 'ENR-2024-002', 'ENROLLED');

INSERT INTO users (id, username, password, role)
VALUES (user_seq.NEXTVAL, 'admin@university.edu', 'admin123', 'ADMIN');

INSERT INTO users (id, username, password, role)
VALUES (user_seq.NEXTVAL, 'john.doe@university.edu', 'student123', 'STUDENT');

COMMIT;