ALTER SESSION SET CURRENT_SCHEMA = PROJECTDB;

SELECT USER as current_user, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') as current_schema FROM dual;

-- Create sequences first
CREATE SEQUENCE STUDENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSTRUCTOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COURSE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENROLLMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

-- Create tables in correct order (no foreign keys first)

-- 1. Students table
CREATE TABLE students (
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL,
    address VARCHAR2(500) NOT NULL,
    date_of_birth DATE NOT NULL
);

-- 2. Instructors table
CREATE TABLE instructors (
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) NOT NULL UNIQUE,
    phone_number VARCHAR2(50) NOT NULL,
    department VARCHAR2(100) NOT NULL,
    office_address VARCHAR2(500)
);

-- 3. Users table
CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) NOT NULL,
    department VARCHAR2(100)
);

-- 4. Courses table (references instructors)
CREATE TABLE courses (
    id NUMBER PRIMARY KEY,
    course_code VARCHAR2(20) NOT NULL UNIQUE,
    course_name VARCHAR2(200) NOT NULL,
    credits NUMBER NOT NULL,
    description VARCHAR2(1000),
    instructor_id NUMBER REFERENCES instructors(id)
);

-- 5. Enrollments table (references students and courses)
CREATE TABLE enrollments (
    id NUMBER PRIMARY KEY,
    student_id NUMBER NOT NULL REFERENCES students(id),
    course_id NUMBER NOT NULL REFERENCES courses(id),
    enrollment_number VARCHAR2(100) UNIQUE,
    grade NUMBER,
    status VARCHAR2(50) DEFAULT 'ENROLLED',
    enrollment_date DATE DEFAULT SYSDATE
);

-- 6. Simple audit log table (for triggers)
CREATE TABLE simple_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    action VARCHAR2(10),
    user_name VARCHAR2(100),
    when_done TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    what_changed VARCHAR2(500)
);

COMMIT;
